In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(7,7)

array([7, 7, 7, 7, 7, 7, 7])

In [7]:
a = np.array([2,4,6,8])
a

array([2, 4, 6, 8])

In [10]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [14]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [16]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr[2] = [7,7,7]

arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 7, 7]])

In [23]:
arr[:,1] = [3,3,3]

arr

array([[1, 3, 3],
       [4, 3, 6],
       [7, 3, 7]])

In [36]:
np.random.seed(2)
np.random.rand(5,2)*100

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [38]:
np.random.randint(1,15,size=(2,3))

array([[ 5, 11, 12],
       [ 4,  8,  7]])

In [42]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [44]:
a*3

array([ 0,  3,  6,  9, 12])

In [46]:
a[a>=2]

array([2, 3, 4])

In [50]:
a.sum()

np.int64(10)